# Generated by Django 4.1.3 on 2022-11-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracc',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
