# Generated by Django 4.1.3 on 2023-01-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccprofile',
            name='image',
            field=models.ImageField(default='default_user_image.png', upload_to='users_images/'),
        ),
    ]
