# Generated by Django 4.1.3 on 2022-11-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_useracc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracc',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='useracc',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
