# Generated by Django 4.1.3 on 2023-01-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraccprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccprofile',
            name='image',
            field=models.ImageField(default='users_images/default_user_image.png', upload_to='users_images/'),
        ),
    ]
