# Generated by Django 4.1.3 on 2022-12-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
